# Constants of the game
import pickle, pygame

try:
	with open('config.bin', 'rb') as f:
		data = pickle.load(f)
		WIDTH = data['width']
		HEIGHT = data['height']
	#WIDTH = 1280
	#HEIGHT = 720
except Exception as e:
	WIDTH = 1280
	HEIGHT = 720
	print('config loading error, setting to defaults (1280, 720)')
	print(e)

DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 360

FPS = 60

OBJECT_MULTIPLYER_WIDTH = WIDTH // DEFAULT_WIDTH
OBJECT_MULTIPLYER_HEIGHT = HEIGHT // DEFAULT_HEIGHT
AVERAGE_MULTIPLYER = (OBJECT_MULTIPLYER_WIDTH+OBJECT_MULTIPLYER_HEIGHT)//2

WINDOW_RESOLUTION = (WIDTH, HEIGHT)

DEFAULT_CASTLE_WIDTH = 200
DEFAULT_CASTLE_HEIGHT = 220
CASTLE_SIZE = (DEFAULT_CASTLE_WIDTH*OBJECT_MULTIPLYER_WIDTH, DEFAULT_CASTLE_HEIGHT*OBJECT_MULTIPLYER_HEIGHT)

DEFAULT_ROAD_WIDTH = DEFAULT_WIDTH
DEFAULT_ROAD_HEIGHT = 247 #DEFAULT_HEIGHT // 2 + 80
ROAD_SIZE = (DEFAULT_ROAD_WIDTH*OBJECT_MULTIPLYER_WIDTH, DEFAULT_ROAD_HEIGHT*OBJECT_MULTIPLYER_HEIGHT)

DEFAULT_HPBAR_WIDTH = 180
DEFAULT_HPBAR_HEIGHT = 15
DEFAULT_HPBAR_SIZE = (DEFAULT_HPBAR_WIDTH*OBJECT_MULTIPLYER_WIDTH, DEFAULT_HPBAR_HEIGHT*OBJECT_MULTIPLYER_HEIGHT)
HPBAR_BACKGROUND_SIZE = DEFAULT_HPBAR_SIZE

DEFAULT_MANABAR_WIDTH = 180
DEFAULT_MANABAR_HEIGHT = 15
DEFAULT_MANABAR_SIZE = (DEFAULT_MANABAR_WIDTH*OBJECT_MULTIPLYER_WIDTH, DEFAULT_MANABAR_HEIGHT*OBJECT_MULTIPLYER_HEIGHT)
MANABAR_BACKGROUND_SIZE = DEFAULT_MANABAR_SIZE

DEFAULT_INFO_FONT_SIZE = 10
INFO_FONT_SIZE = DEFAULT_INFO_FONT_SIZE*AVERAGE_MULTIPLYER

DEFAULT_MONSTER_SIZE = (50, 50)
MONSTER_SIZE = (DEFAULT_MONSTER_SIZE[0]*OBJECT_MULTIPLYER_WIDTH, DEFAULT_MONSTER_SIZE[1]*OBJECT_MULTIPLYER_HEIGHT)

MANA_ADD_TIMER = 0.05

DEFAULT_TOWN_SHOOTER_SIZE = (14, 21)
TOWN_SHOOTER_SIZE = (DEFAULT_TOWN_SHOOTER_SIZE[0]*OBJECT_MULTIPLYER_WIDTH, DEFAULT_TOWN_SHOOTER_SIZE[1]*OBJECT_MULTIPLYER_HEIGHT)

DEFAULT_SETTINGS_BUTTON_SZIE = (25, 25)
SETTINGS_BUTTON_SIZE = (DEFAULT_SETTINGS_BUTTON_SZIE[0]*OBJECT_MULTIPLYER_WIDTH, DEFAULT_SETTINGS_BUTTON_SZIE[1]*OBJECT_MULTIPLYER_HEIGHT)

DEFAULT_SETTINGS_WINDOW_SIZE = (200, 225)
SETTINGS_WINDOW_SIZE = (DEFAULT_SETTINGS_WINDOW_SIZE[0]*OBJECT_MULTIPLYER_WIDTH, DEFAULT_SETTINGS_WINDOW_SIZE[1]*OBJECT_MULTIPLYER_HEIGHT)

DEFAULT_APPLY_SETTIGS_BUTTON_SIZE = (120, 50)
APPLY_SETTIGS_BUTTON_SIZE = (DEFAULT_APPLY_SETTIGS_BUTTON_SIZE[0]*OBJECT_MULTIPLYER_WIDTH, DEFAULT_APPLY_SETTIGS_BUTTON_SIZE[1]*OBJECT_MULTIPLYER_HEIGHT)

NUMBERS_KEYS = [pygame.K_1, pygame.K_2, pygame.K_3, pygame.K_4, pygame.K_5, pygame.K_6, pygame.K_7, pygame.K_8, pygame.K_9, pygame.K_0]